#!/bin/bash
# Última actualización: 09/03/2022
cd /
# Se descarga Firefox
wget http://www.styluslabs.com/write/write-latest.tar.gz
wget https://lh4.ggpht.com/If8AjdadABvi_CXqGZnx47ZqbHqTlZwcgXFgvmICf5I_M01TjBatpkcQB_Dr-L32yA=w300
cd /usr/local/
echo 'Se va a instalar en /usr/local/...'
read -p "Ingresa el nombre del directorio principal de instalacion, si no existe se creará: " DIRINST
if [ -d $DIRINST ];
	then
		echo 'El directorio ya existe...'
		echo '>>> Ingresando...'
		cd $DIRINST
	else
		echo 'El directorio no existe...'
		echo 'Creando directorio...'
		mkdir $DIRINST
		echo 'Directorio creado...'
		echo '>>> Ingresando...'
		cd $DIRINST
fi
sleep 2
mv /write-latest.tar.gz /usr/local/$DIRINST
tar xzvf write-latest.tar.gz
mv Write write
mv /If8AjdadABvi_CXqGZnx47ZqbHqTlZwcgXFgvmICf5I_M01TjBatpkcQB_Dr-L32yA\=w300 /usr/local/$DIRINST/write/icon.png
#
#App a Menú
cd /usr/share/applications/
touch write.desktop
echo '[Desktop Entry]' > write.desktop
echo 'Version=v3 Build:440;e7f02ce' >> write.desktop
echo 'Name=Write' >> write.desktop
echo 'Comment=Note Editor' >> write.desktop
echo 'Exec=/usr/local/'$DIRINST'/write/Write' >> write.desktop
echo 'Icon=/usr/local/'$DIRINST'/write/icon.png' >> write.desktop
echo 'Categories=Office;' >> write.desktop
echo 'Terminal=false' >> write.desktop
echo 'Type=Application' >> write.desktop
cd /usr/local/$DIRINST/write/
#
#Remove
touch remove.sh
echo "#!/bin/bash" > remove.sh
echo "echo '------------------------------'" >> remove.sh
echo "echo 'Removiendo...'" >> remove.sh
echo "echo -ne '[===>                                    ]( 8.33%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[=========>                              ](16.66%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[============>                           ](24.99%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[===============>                        ](33.32%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[==================>                     ](41.65%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[=====================>                  ](49.98%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[========================>               ](58.31%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[===========================>            ](66.64%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[==============================>         ](74.97%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[=================================>      ](83.30%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[====================================>   ](91.64%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '[=======================================>](100.00%)\r';sleep 0.2" >> remove.sh
echo "echo -ne '\n'" >> remove.sh
echo 'cd /' >> remove.sh
echo 'rm -rf /usr/share/applications/write.desktop' >> remove.sh
echo 'rm -rf /usr/local/'$DIRINST'/write/' >> remove.sh
echo "echo 'Completado!'" >> remove.sh
echo "echo '------------------------------'" >> remove.sh
echo 'exit' >> remove.sh
chmod 744 remove.sh
#
#README
touch README.txt
echo 'Write Stylus' > README.txt
echo 'Idioma=en_US' >> README.txt
echo 'Version=v3 Build:440;e7f02ce' >> README.txt
echo 'Arquitectura=x86' >> README.txt
echo 'Esta es una instalación no invasiva.' >> README.txt
echo 'Para desinstalar ejecute el fichero remove.sh como root.' >> README.txt
echo '' >> README.txt
echo 'http://www.styluslabs.com/' >> README.txt
echo '' >> README.txt
echo 'xaxlm' >> README.txt
#
# Limpieza
cd /
echo '------------------------------'
echo 'Limpiando...'
echo -ne '[===>                                    ]( 8.33%)\r';sleep 0.2
echo -ne '[=========>                              ](16.66%)\r';sleep 0.2
echo -ne '[============>                           ](24.99%)\r';sleep 0.2
echo -ne '[===============>                        ](33.32%)\r';sleep 0.2
echo -ne '[==================>                     ](41.65%)\r';sleep 0.2
echo -ne '[=====================>                  ](49.98%)\r';sleep 0.2
echo -ne '[========================>               ](58.31%)\r';sleep 0.2
echo -ne '[===========================>            ](66.64%)\r';sleep 0.2
echo -ne '[==============================>         ](74.97%)\r';sleep 0.2
echo -ne '[=================================>      ](83.30%)\r';sleep 0.2
echo -ne '[====================================>   ](91.64%)\r';sleep 0.2
echo -ne '[=======================================>](100.00%)\r';sleep 0.2
echo -ne '\n'
rm -rf /usr/local/$DIRINST/write-latest.tar.gz
echo 'Completado!'
echo '------------------------------'
exit
